version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.1.5
    ports:
      - 3000:3000
